// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn5e5WJkTp_xjAQ9zMCOptMfn2VcXXWDM',
    appId: '1:753678834169:web:6eeada85ef870141d04528',
    messagingSenderId: '753678834169',
    projectId: 'fir-login-crud-83dfb',
    authDomain: 'fir-login-crud-83dfb.firebaseapp.com',
    storageBucket: 'fir-login-crud-83dfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCV4aCrWom7yERnIfR-A32CizwD8OoRD0',
    appId: '1:753678834169:android:1fad685d44735459d04528',
    messagingSenderId: '753678834169',
    projectId: 'fir-login-crud-83dfb',
    storageBucket: 'fir-login-crud-83dfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKPGSda8vJ2Y_6pCz_PO5mpUKVTf2UkNM',
    appId: '1:753678834169:ios:34f069479128601fd04528',
    messagingSenderId: '753678834169',
    projectId: 'fir-login-crud-83dfb',
    storageBucket: 'fir-login-crud-83dfb.appspot.com',
    iosClientId: '753678834169-0mgpt7hl6l3ps6ddbuojg54a82pihl5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKPGSda8vJ2Y_6pCz_PO5mpUKVTf2UkNM',
    appId: '1:753678834169:ios:34f069479128601fd04528',
    messagingSenderId: '753678834169',
    projectId: 'fir-login-crud-83dfb',
    storageBucket: 'fir-login-crud-83dfb.appspot.com',
    iosClientId: '753678834169-0mgpt7hl6l3ps6ddbuojg54a82pihl5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLogin',
  );
}
